@baseUrl = http://localhost:3333
@attendeeId = nJhS9s9d7I4A
@eventId = 5db75da9-2e6c-44c3-a2db-8e506e9b08ce

###

# @name createEvent
POST {{baseUrl}}/api/events
Content-Type: application/json

{
  "title": "Unite summit 6",
  "details": "Um evento para apaixonados por tecnologia e programação.",
  "maximumAttendees": 2
}

###

# @name registerForEvent
POST {{baseUrl}}/api/events/{{eventId}}/attendees
Content-Type: application/json

{
  "name": "Lucas Patrick",
  "email": "lucas.patrick3@gmail.com"
}

###

# @name getEventById
GET {{baseUrl}}/api/events/{{eventId}}

###

# @name getEventAttendees
GET {{baseUrl}}/api/events/{{eventId}}/attendees?query=Lucas

###

# @name getAttendeeBadge
GET {{baseUrl}}/api/attendees/{{attendeeId}}/badge

###

# @name makeCheckIn
GET {{baseUrl}}/api/attendees/{{attendeeId}}/check-in
