@baseUrl = http://localhost:3333
@attendeeId = nJhS9s9d7I4A
@eventId = d7e7a563-c3ea-4510-b91f-19d88a938a51

###

# @name createEvent
POST {{baseUrl}}/api/events
Content-Type: application/json

{
  "title": "Unite summit",
  "details": "Um evento para apaixonados por tecnologia e programação.",
  "maximumAttendees": 2
}

###

# @name registerForEvent
POST {{baseUrl}}/api/events/{{eventId}}/attendees
Content-Type: application/json

{
  "name": "Lucas Patrick",
  "email": "lucas.patrick3@gmail.com"
}

###

# @name getEventById
GET {{baseUrl}}/api/events/{{eventId}}

###

# @name getEventAttendees
GET {{baseUrl}}/api/events/{{eventId}}/attendees?query=Lucas

###

# @name getAttendeeBadge
GET {{baseUrl}}/api/attendees/{{attendeeId}}/badge

###

# @name makeCheckIn
GET {{baseUrl}}/api/attendees/{{attendeeId}}/check-in
